# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-19 14:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rapport',
            name='description',
        ),
        migrations.RemoveField(
            model_name='rapport',
            name='price',
        ),
        migrations.RemoveField(
            model_name='rapport',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='rapport',
            name='title',
        ),
        migrations.AddField(
            model_name='rapport',
            name='action',
            field=models.TextField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='rapport',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 19, 16, 35, 44, 324678)),
        ),
        migrations.AddField(
            model_name='rapport',
            name='design',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='rapport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='rapport',
            name='name',
            field=models.TextField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='rapport',
            name='note',
            field=models.TextField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rapport',
            name='section',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
