# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-19 14:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_auto_20190719_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 19, 16, 35, 51, 773374)),
        ),
    ]
