# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-19 22:18
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_auto_20190719_1900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 20, 0, 18, 13, 908580)),
        ),
    ]
