# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-19 22:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0006_auto_20190720_0034'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 20, 0, 41, 53, 908734)),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='reportNr',
            field=models.TextField(blank=True, default='<reports.models.MyNumbers object at 0x000001D715396518>'),
        ),
    ]
