# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-20 23:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0008_auto_20190720_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 21, 1, 15, 20, 454822)),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='reportNr',
            field=models.TextField(blank=True, default='<bound method BaseManager._get_queryset_methods.<locals>.create_method.<locals>.manager_method of <reports.models.RapportManager object at 0x000001BE20E78550>>'),
        ),
    ]
