# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-22 08:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0017_auto_20190721_2059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='date',
            field=models.DateField(default=datetime.datetime(2019, 7, 22, 10, 58, 38, 319862)),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='reportNr',
            field=models.TextField(blank=True, default='<bound method BaseManager._get_queryset_methods.<locals>.create_method.<locals>.manager_method of <reports.models.RapportManager object at 0x00000185B39A8630>>'),
        ),
    ]
