# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-22 22:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0019_auto_20190722_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='reportNr',
            field=models.TextField(blank=True, default='<bound method BaseManager._get_queryset_methods.<locals>.create_method.<locals>.manager_method of <reports.models.RapportManager object at 0x00000268BC2E6630>>'),
        ),
    ]
