# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-22 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0021_auto_20190723_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='reportNr',
            field=models.TextField(blank=True, default='10001'),
        ),
    ]
