# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-25 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0023_auto_20190725_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='reportNr',
            field=models.TextField(blank=True, default='101'),
        ),
    ]
