# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-25 10:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0024_auto_20190725_1215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='files'),
        ),
    ]
