# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-25 21:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0025_auto_20190725_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('photo', models.FileField(upload_to='data/media/%Y/%m/%d')),
            ],
        ),
    ]
