# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-27 09:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0028_delete_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
