# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-27 09:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0029_auto_20190727_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='anstNr',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='atgard',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='avd',
            field=models.TextField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='enhetsNr',
            field=models.TextField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='namn',
            field=models.TextField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='reportNr',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='ritningNr',
            field=models.TextField(blank=True, max_length=20, null=True),
        ),
    ]
