# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-07-27 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0030_auto_20190727_1151'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='anstNr',
            field=models.TextField(blank=True, default='43011', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='atgard',
            field=models.TextField(blank=True, default='Ökade hastigheten på bandet 5% p.g.a större flöde', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='avd',
            field=models.TextField(blank=True, default='R8', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='enhetsNr',
            field=models.TextField(blank=True, default='B394', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='namn',
            field=models.TextField(blank=True, default='Erik Johansson', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='reportNr',
            field=models.TextField(blank=True, default='101'),
        ),
        migrations.AlterField(
            model_name='rapport',
            name='ritningNr',
            field=models.TextField(blank=True, default='3-1711', max_length=20, null=True),
        ),
    ]
