# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-08-01 20:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0032_auto_20190728_1246'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rapport',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
